app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    """Accepts a nickname and a room."""
    name = StringField('Name', validators=[DataRequired()])
    room = StringField('Room', validators=[DataRequired()])
    submit = SubmitField('Enter Chatroom')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
from .forms import LoginForm


@main.route('/', methods=['GET', 'POST'])
def index():
    """Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('index.html', form=form)


@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('photo.html', name=name, room=room)

app/templates/index.html
<html>
    <head>
        <title>PhotoChat</title>
    </head>
    <body>
        <h1>PhotoChat</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            {{ form.room.label }}: {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>
    </body>
</html>

app/templates/photo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PhotoChat: {{ room }}</title>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="//cdn.socket.io/4.4.1/socket.io.min.js"></script>
    <script type="text/javascript" charset="utf-8">
        let socket;

        $(document).ready(function () {
            socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');

            socket.on('connect', function() {  
                socket.emit('joined', {});
            });
            
            socket.on('status', function(data) {
                $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                $('#chat').scrollTop($('#chat')[0].scrollHeight);
            });

            socket.on("image", function(data) {
                var messageContainer = document.getElementById('message-container');

                var arrayBufferView = new Uint8Array(data['image']);
                var blob = new Blob( [ arrayBufferView ], { type: "image/jpeg" } );
                var img_url = URL.createObjectURL(blob);
                var img = document.createElement("img");
                img.src = img_url;
                img.style.width = '50%';

                messageContainer.appendChild(img);
            });
        });

        function upload() {
            var file = document.getElementById('files').files[0];
            var fileReader = new FileReader();
            fileReader.readAsArrayBuffer(file);

            fileReader.onload = function(e) {
                var arrayBuffer = fileReader.result;

                socket.emit('image-upload', { 
                    name: file.name, 
                    type: file.type, 
                    size: file.size, 
                    binary: arrayBuffer 
                });
            };
        };

        function leave_room() {
            socket.emit('left', {}, function() {
                socket.disconnect();
                window.location.href = "{{ url_for('main.index') }}";
            });
        };
    </script>
</head>

<style>
    main {
        display: flex;
        flex-direction: row;
    }
</style>

<body>
    <div class="main">
        <div>
            <form action="">
                <input type="file" id="files" accept="image/*" />
                <button type="button" id="btn" onclick="upload();"> Send </button>
            </form>
            <div id="message-container"></div>
            <a href="#" onclick="leave_room();">Leave this room</a>
        </div>
        <div>
            <textarea id="chat" cols="80" rows="20" disabled="true"></textarea><br><br>
        </div>
    </div>
</body>
</html>